export const ActionTypes = {  
    CORRECT_RESPONSE_ARRAY: "app/containers/ImageArray/CORRECT_RESPONSE_ARRAY",
    USER_RESPONSE_ARRAY: "app/containers/ImageArray/USER_RESPONSE_ARRAY",
    IMAGE_FILENAME_ARRAY: "app/containers/ImageArray/IMAGE_FILENAME_ARRAY",
    IMAGE_FILENAME_LENGTH: "app/containers/ImageArray/IMAGE_FILENAME_LENGTH",
    PREDICTIVE_IMAGE_FILENAME_ARRAY: "app/containers/ImageArray/PREDCTIVE_IMAGE_FILENAME_ARRAY",
    PREDICTIVE_IMAGE_FILENAME_LENGTH: "app/containers/ImageArray/PREDICTIVE_IMAGE_FILENAME_LENGTH",
    IMAGE_SET: "app/containers/ImageArray/IMAGE_SET",
    SCORING_ARRAY: "app/containers/ImageArray/SCORING_ARRAY",
    FINAL_FILENAME_ARRAY: "app/containers/ImageArray/FINAL_FILENAME_ARRAY",
    IMAGE_SET_STAGE_ONE: "app/containers/ImageArray/IMAGE_SET_STAGE_ONE",
    IMAGE_SET_STAGE_TWO: "app/containers/ImageArray/IMAGE_SET_STAGE_TWO",
    IMAGE_SET_STAGE_THREE: "app/containers/ImageArray/IMAGE_SET_STAGE_THREE",
    CORRECT_SCORESRRAY: "app/containers/ImageArray/CORRECT_SCORESRRAY",
    NBACK_INDEX: "app/containers/ImageArray/NBACK_INDEX",
    PREDICTIVE_INDEX: "app/containers/ImageArray/PREDICTIVE_INDEX",
}