export const ActionTypes = {  
    CORRECT_RESPONSE_ARRAY: "app/containers/PhotoSpace/CORRECT_RESPONSE_ARRAY",
    USER_RESPONSE_ARRAY: "app/containers/PhotoSpace/USER_RESPONSE_ARRAY",
    IMAGE_FILENAME_ARRAY: "app/containers/PhotoSpace/IMAGE_FILENAME_ARRAY",
    IMAGE_FILENAME_LENGTH: "app/containers/PhotoSpace/IMAGE_FILENAME_LENGTH",
    PREDICTIVE_IMAGE_FILENAME_ARRAY: "app/containers/PhotoSpace/PREDCTIVE_IMAGE_FILENAME_ARRAY",
    PREDICTIVE_IMAGE_FILENAME_LENGTH: "app/containers/PhotoSpace/PREDICTIVE_IMAGE_FILENAME_LENGTH",
}