export const ActionTypes = {  
    CORRECT_RESPONSE_ARRAY: "app/containersn-back-image-array/CORRECT_RESPONSE_ARRAY",
    USER_RESPONSE_ARRAY: "app/containersn-back-image-array/USER_RESPONSE_ARRAY",
    IMAGE_FILENAME_ARRAY: "app/containersn-back-image-array/IMAGE_FILENAME_ARRAY",
    IMAGE_FILENAME_LENGTH: "app/containersn-back-image-array/IMAGE_FILENAME_LENGTH",
    PREDICTIVE_IMAGE_FILENAME_ARRAY: "app/containersn-back-image-array/PREDCTIVE_IMAGE_FILENAME_ARRAY",
    PREDICTIVE_IMAGE_FILENAME_LENGTH: "app/containersn-back-image-array/PREDICTIVE_IMAGE_FILENAME_LENGTH",
    IMAGE_SET: "app/containersn-back-image-array/IMAGE_SET",
    SCORING_ARRAY: "app/containersn-back-image-array/SCORING_ARRAY",
    FINAL_FILENAME_ARRAY: "app/containersn-back-image-array/FINAL_FILENAME_ARRAY",
    IMAGE_SET_STAGE_ONE: "app/containersn-back-image-array/IMAGE_SET_STAGE_ONE",
    IMAGE_SET_STAGE_TWO: "app/containersn-back-image-array/IMAGE_SET_STAGE_TWO",
    IMAGE_SET_STAGE_THREE: "app/containersn-back-image-array/IMAGE_SET_STAGE_THREE",
    CORRECT_SCORESRRAY: "app/containersn-back-image-array/CORRECT_SCORESRRAY",
    NBACK_INDEX: "app/containersn-back-image-array/NBACK_INDEX",
    PREDICTIVE_INDEX: "app/containersn-back-image-array/PREDICTIVE_INDEX",
}